CREATE TABLE `daka_info` (
  `INFO_ID`     VARCHAR(100) PRIMARY KEY,
  `NAME`        VARCHAR(100) NOT NULL,
  `DISTANCE`    VARCHAR(100) NOT NULL,
  `DATE`        DATE         NOT NULL,
  `CREATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP,
  `UDPATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `daka_user` (
  `USER_ID`     VARCHAR(100) PRIMARY KEY,
  `USERNAME`    VARCHAR(100) NOT NULL,
  `CREATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP,
  `UDPATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `daka_user_password` (
  `USER_ID`     VARCHAR(100) PRIMARY KEY,
  `PASSWORD`    VARCHAR(100) NOT NULL,
  `CREATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP,
  `UDPATE_TIME` DATETIME     NULL    DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
);
